///////////////////////////////////////////////////////////
//  IAlgorithm.cs
//  Implementation of the Interface IAlgorithm
//  Generated by Enterprise Architect
//  Created on:      24-4月-2016 9:16:28
//  Original author: FH
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using AnalyzeLibrary;
using AnalyzeLibrary.result;

namespace AnalyzeLibrary
{
	/// <summary>
	/// 算法接口
	/// </summary>
	public interface IAlgorithm   {

		/// <summary>
		/// pro
		/// </summary>
	
		AnalyzeResult calculation();
	}//end IAlgorithm

}//end namespace analyze